import { useState } from 'react';
import { FolderOpen, Plus, Pencil, Trash2, X } from 'lucide-react';
import { t } from './i18n';
import type { DocumentRecord, Space } from './types';
export function Spaces({ spaces, documents, openIds, onRefresh, onOpen, notify }: { spaces: Space[]; documents: DocumentRecord[]; openIds: string[]; onRefresh: () => Promise<void>; onOpen: (ids: string[]) => void; notify: (message: string) => void }) {
  const [editing, setEditing] = useState<Space | null>(), [name, setName] = useState(''), [ids, setIds] = useState<string[]>([]);
  const edit = (space: Space | null) => { setEditing(space); setName(space?.name || ''); setIds(space?.documentIds || openIds); };
  const save = async () => { try { await window.hawk.saveSpace(editing?.id || null, name, ids); await onRefresh(); setEditing(undefined); } catch (error) { notify(String(error)); } };
  return <section className="spaces-section"><div className="library-heading"><h3>{t('Мои пространства')}</h3><button className="icon-button" aria-label={t('Создать пространство')} onClick={() => edit(null)}><Plus size={18}/></button></div>
    {spaces.map(space => <div className="space-row" key={space.id}><button className="space-open" aria-label={t('Открыть пространство ') + space.name} onClick={() => onOpen(space.documentIds)} disabled={!space.documentIds.length}><FolderOpen size={17}/><span>{space.name}</span><small>{space.documentIds.length}</small></button><button className="icon-button" aria-label={t('Редактировать пространство ') + space.name} onClick={() => edit(space)}><Pencil size={14}/></button><button className="icon-button" aria-label={t('Удалить пространство ') + space.name} onClick={() => void window.hawk.removeSpace(space.id).then(onRefresh).catch(error => notify(String(error)))}><Trash2 size={14}/></button></div>)}
    {!spaces.length && <p className="spaces-empty">{t('Нет пространств. Объедините документы в группу.')}</p>}
    {editing !== undefined && <div className="modal-shade" onClick={() => setEditing(undefined)}><form className="settings-dialog space-dialog" role="dialog" aria-modal="true" aria-label={t(editing ? 'Изменить пространство' : 'Создать пространство')} onClick={event => event.stopPropagation()} onSubmit={event => { event.preventDefault(); void save(); }}><header><h2>{t(editing ? 'Изменить пространство' : 'Создать пространство')}</h2><button className="icon-button" type="button" aria-label={t('Отменить')} onClick={() => setEditing(undefined)}><X size={18}/></button></header><label className="space-name">{t('Название пространства')}<input autoFocus aria-label={t('Название пространства')} required maxLength={100} value={name} onChange={event => setName(event.target.value)}/></label><div className="space-select-heading"><h3>{t('Документы пространства')}</h3><button type="button" onClick={() => setIds(openIds)}>{t('Сохранить открытые вкладки')}</button></div><div className="space-documents">{documents.map(doc => <label key={doc.id}><input type="checkbox" checked={ids.includes(doc.id)} onChange={event => setIds(previous => event.target.checked ? [...previous, doc.id] : previous.filter(id => id !== doc.id))}/><span title={doc.path}>{doc.title}<small>{doc.path}</small></span></label>)}</div><button className="primary" type="submit" disabled={!name.trim()}>{t('Сохранить')}</button></form></div>}
  </section>;
}
